#!/usr/bin/env perl  
# Khushbu Patel 3-28-18
# parsing launch_set.log file generated by Lyve-SET/1.1.4f 
# Change path before executing this script





use warnings;
use strict;

	my @array;

	my $str5 = `cat /scicomp/home/oix2/EDLB/projects/Surveillance/Shigella/Local_WA_flexneri_march2018/lyve-SET_v1.1.4f_ext-ref_95-3008_clusterA_3-12-18/log/launch_set.log | grep 'reportMaskedGenomes: '`;
	
	

	@array = split ":|\n", $str5; 
	
	foreach(@array)	
	{
			
			if($_ =~/\sPNU.+/g)
			{
			print $_."\n";
			}
	
		
	}
	
		
	
